grails-app/domain/com/intelligrape/locateMe/domain/FaceBookUser.groovy
package com.intelligrape.locateMe.domain

import javax.jdo.annotations.*;
// import com.google.appengine.api.datastore.Key;

@PersistenceCapable(identityType = IdentityType.APPLICATION, detachable="true")
class FaceBookUser {

	@PrimaryKey
    @Persistent(valueStrategy = IdGeneratorStrategy.IDENTITY)
	Long id

	@Persistent
	String userId
	@Persistent
	String accessToken
	@Persistent
	String name
	@Persistent
	String picture
	@Persistent
	String email
	@Persistent
	boolean dirty=false

    static constraints = {
    	id( visible:false)
	}
}

grails-app/controllers/com/intelligrape/locateMe/controller/FaceBookController.groovy
package com.intelligrape.locateMe.controller

import grails.converters.JSON

class FaceBookController {
	def grailsApplication

	def index = {
		redirect(url: facebookAuthorizeUrl)
	}

	def accessDenied = {
	}

	def requestAuthorizationCode = {
		if (params.error) {
			log.info "Possibly user denied the application or login failed"
			redirect(action: 'accessDenied', params: params)
			return
		}
		if (!params.code) {
			log.info "User directly came to this url"
			redirect action: index
			return
		}
		String accessTokenResponse = getAuthenticateApplicationUrl(params.code).toURL().getText('ISO-8859-1')
		if (accessTokenResponse.contains('access_token=')) {
			String[] resp = accessTokenResponse.split('access_token=')
			String accessToken = resp[1]
			session['fb_token'] = accessToken
			redirect(action: "userInfo")
		} else {
			redirect(action: 'index')
		}
	}

	def userInfo = {
		if (!getFaceBookToken()) {
			redirect(action: 'index')
		}
		String currentUserId = params.id ?: getUserId()
		println "User Id to display detail : " + currentUserId
		String urlUserDetailResponseText = getUserDetailUrl(currentUserId).toURL().getText('ISO-8859-1')
		def userDetail = JSON.parse(urlUserDetailResponseText)
		[
				userInfo: userDetail,
				loggedInUserId: userId,
				currentUserId: currentUserId,
		]
	}
	def test={
		[loggedInUserId:getUserId()]
	}

	private String getFacebookAuthorizeUrl() {
		return grailsApplication.config.facebook.oauthUrl + "?" +
				[
						"client_id": grailsApplication.config.facebook.applicationId,
						"redirect_uri": createLink(absolute: true, action: 'requestAuthorizationCode'),
						"scope": grailsApplication.config.facebook.permissions
				].collect {attribute, value -> "${attribute}=${value.encodeAsURL()}"}.join("&")
	}

	private String getAuthenticateApplicationUrl(String facebookAuthCode) {
		return grailsApplication.config.facebook.graphApiBasicUrl + "oauth/access_token?" +
				[
						"client_id": grailsApplication.config.facebook.applicationId,
						"client_secret": grailsApplication.config.facebook.secretKey,
						"code": facebookAuthCode,
						"redirect_uri": createLink(absolute: true, action: 'requestAuthorizationCode'),
						"scope": grailsApplication.config.facebook.permissions
				].collect {attribute, value -> "${attribute}=${value.encodeAsURL()}"}.join("&")
	}

	private String getUserDetailUrl(String currentUserId) {
		return grailsApplication.config.facebook.graphApiBasicUrl + currentUserId + "?access_token=${faceBookToken.encodeAsURL()}"
	}

	private String getUserId() {
        String urlUserDetailResponseText = getUserDetailUrl("me").toURL().getText('ISO-8859-1')
        def userDetail = JSON.parse(urlUserDetailResponseText)
        return userDetail?.id
	}

	private String getFaceBookToken() {
		return session['fb_token']
	}
}

grails-app/controllers/com/intelligrape/locateMe/controller/FaceBookUserController.groovy
package com.intelligrape.locateMe.controller

import com.google.appengine.api.datastore.*
import com.intelligrape.locateMe.domain.FaceBookUser

class FaceBookUserController {
	def scaffold = FaceBookUser
}

grails-app/views/faceBook/accessDenied.gsp
<html>
<head>
	<title>Login Failure</title>
	<style type="text/css">
	.message {
		border: 1px solid black;
		padding: 5px;
		background-color: #E9E9E9;
	}
	</style>
</head>

<body>
<h1>Facebook login failed</h1>
<h2>${error}</h2>

<div class="message">
	<strong>error_reason:</strong> ${error_reason}<br/>
	<strong>Description:</strong> ${error_description}<br/>
</div>
<div>
	<g:link controller="faceBook">Try again</g:link>
</div>
</body>
</html>

grails-app/views/faceBook/test.gsp
<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
	<meta name="layout" content="main"/>
	<title>JavaScript SDK test</title>
</head>
<body>
<div id="fb-root"></div>
<script src="http://connect.facebook.net/en_US/all.js"></script>
<script>
	var currentUserId = "${loggedInUserId}";
	FB.init({
		appId: '186418821373054',
		status: true,
		cookie: true,
		xfbml: true,
		channelUrl  : "${grailsApplication.config.grails.serverURL}/channel.html"  // custom channel
	});
	FB.api(
	{
		method: "fql.query",
		query: "SELECT uid, name,sex, pic_small, birthday, hometown_location, current_location FROM user WHERE uid = " + currentUserId +
			" OR uid IN (SELECT uid2 FROM friend WHERE uid1 =" + currentUserId + ")"
	}, function(response) {
			console.debug(response)
		}
		);

	function postOnWall(msg) {
		FB.ui(
		{
			method: 'feed',
			name: 'Bhagwat Status',
			link: 'http://developers.facebook.com/docs/reference/dialogs/',
			caption: 'Reference Documentation',
			description: 'Dialogs provide a simple, consistent interface for applications to interface with users.',
			message: 'Facebook Dialogs are easy!'
		},
			function(response) {
				if (response && response.post_id) {
					alert('Post was published.');
				} else {
					alert('Post was not published.');
				}
			}
			)
	}

</script>
<button onclick="postOnWall('hello from here')" value="Click"/>
</body>
</html>

grails-app/views/faceBook/userInfo.gsp
<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <meta name="layout" content="main"/>
    <title><g:message code="where.are.your.friends" default="Where are your friends?"/></title>
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
    <script type="text/javascript">
        var applicationID = "${grailsApplication.config.facebook.applicationId}";
        var currentUserId = "${currentUserId}";
        var applicationRoot = "${grailsApplication.config.grails.serverURL}/faceBook/userInfo/";
        var applicationServerUrl = "${grailsApplication.config.grails.serverURL}";
    </script>
    <g:javascript src="findme.facebook-9.js"/>
    <g:javascript src="jquery.flash.js"/>
</head>
<body style="margin:5px;">
<div id="fb-root"></div>
<script type="text/javascript" src="http://connect.facebook.net/en_US/all.js"></script>
<script type="text/javascript">
    FB.init({
        appId: applicationID,
        status: true,
        cookie: true,
        xfbml: true,
        channelUrl  : "${grailsApplication.config.grails.serverURL}/channel.html"  // custom channel
    });
    FB.Canvas.setAutoResize();
</script>
<div id="flash"></div>
<div id="login-flow">
    <fb:login-button perms="${grailsApplication.config.facebook.permissions}" show-faces="true"></fb:login-button>
</div>
<table>
    <tr>
        <td>
            <h2>
                Welcome
                <a href="${createLink(action: 'userInfo', id: loggedInUserId)}">
                    ${userInfo.name}
                </a>
            </h2>
        </td>
        <td>
            <div class="navigation">
                Search By
                <g:radio value="hometown_location" name="searchBy" checked="true"/>Home town
                <g:radio value="current_location" name="searchBy"/>Current town
                <input type="button" onclick="$('#friendList .head').next().hide();" value="${message(code: 'collapse.all')}"/>
                <input type="button" onclick="$('#friendList .head').next().show();" value="${message(code: 'expand.all')}"/>
                <input type="button" onclick="showGoogleMapLineConnections();" value="Connect line"/>
                <input type="button" onclick="postOnWall();" value="Post on wall"/>
            </div>
        </td>
    </tr>
    <tr>
        <td>
            Search : <googleMap:searchAddressInput onComplete="updateHomeLocation" name="searchAddress"
                    map="googleMap" width="450" minChars="3" scrollHeight="420" style="width:80%;"/> <br/>
            <googleMap:map
                    name="googleMap"
                    mapDivId="map_canvas"
                    zoom="18"
                    homeMarker="[latitude: 40.729883, longitude: -73.990986, draggable: false, visible:false, content: 'Liberty State Park']"
                    mapTypeId="google.maps.MapTypeId.ROADMAP"/>
            <div id="map_canvas" style="width: 600px; height: 410px;"></div>
        </td>
        <td>
            <div id="friend-count"></div>
            <div id="friendList" style="width: 600px; height: 400px;overflow:auto;">
            </div>
        </td>
    </tr>
</table>
</body>
</html>

grails-app/views/layouts/main.gsp
<!DOCTYPE html>
<html>
<head>
	<title><g:layoutTitle default="Grails"/></title>
	<link rel="stylesheet" href="${resource(dir: 'css', file: 'main1.css')}"/>
	<link rel="shortcut icon" href="${resource(dir: 'images', file: 'icon.jpeg')}" type="image/x-icon"/>
	<g:javascript library="jquery" plugin="jquery"/>
	<googleMap:init version="3.2" sensor="false" addressAutoComplete="true"/>
	<g:layoutHead/>
</head>
<body>
<g:layoutBody/>
</body>
</html>